/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package statsmodel;

import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYDifferenceRenderer;
import org.jfree.data.general.DatasetUtilities;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
//import statsmodel.Logic.IAreaType;

/**
 *
 * @author st8511x
 */
public class frmExtremities extends javax.swing.JFrame { //implements IAreaType{

    ChartPanel chartPanel;
    JFreeChart chart;

    public frmExtremities() {
        initComponents();
        chartPanel = new ChartPanel(chart);//prevents new graphs from appending
        txtMean.setText("0");
        txtSD.setText("1");
        txtX1.setText("-2");
        txtX2.setText("2");
       

    }

    public void colour_AreaEnds(
            double meanModulo,
            double sdModulo,
            XYDataset dataset,
            XYPlot plot,
            double a,
            double b) {
        Number no = DatasetUtilities.findMaximumRangeValue(dataset);

        XYDifferenceRenderer renderer = new XYDifferenceRenderer(Color.CYAN, Color.CYAN, false);
        renderer.setNegativePaint(new Color(0, 0, 0, 0));//hides rectangle above curve cause literally a block
        plot.setRenderer(0, renderer);

        plot.getRenderer().setSeriesPaint(0, Color.CYAN);

        plot.getRenderer().setSeriesPaint(1, (new Color(0, 0, 0, 0)));

        XYSeries line = new XYSeries("line");//sequence of data items in (x,y) format
/*
         line.add((meanModulo - (4 * sdModulo)), 0);// a
         line.add((meanModulo - (2 * sdModulo)), 0);//b

         line.add((meanModulo - (2 * sdModulo)), no);//b
         line.add((meanModulo + (sdModulo)), no);//c

         line.add((meanModulo + sdModulo), 0);//c
         line.add((meanModulo + (4 * sdModulo)), 0);//d
         */

        /*XYSeriesCollection: collection of XYSeries objects
         */
        
        line.add((meanModulo - (4 * sdModulo)), 0);// infinity left 
        line.add(a, 0);//user input x1

        /*an invisible 'block' is placed between the two
         x values to give the illusion that only the ends of the graphs area shaded in
         */
        line.add(a, no);
        line.add(b, no);//user input x2

        line.add(b, 0);
        line.add((meanModulo + (4 * sdModulo)), 0);//infinity right

        ((XYSeriesCollection) dataset).addSeries(line); //add the two lines to the exisiting normal dist. graph
        renderer.setSeriesPaint(0, Color.BLACK);//sets outline colour to black

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        txtX2 = new javax.swing.JTextField();
        txtSD = new javax.swing.JTextField();
        txtMean = new javax.swing.JTextField();
        btnDisplay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlGraphDisplay = new javax.swing.JPanel();
        txtX1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calculate Area");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(400, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jTextField4.setText("x>= user input value");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 80));
        getContentPane().add(txtX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 90, 30));

        txtSD.setText("1.2");
        getContentPane().add(txtSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 110, 30));

        txtMean.setText("10");
        txtMean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMeanActionPerformed(evt);
            }
        });
        getContentPane().add(txtMean, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 90, 30));

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 120, 40));

        jLabel1.setText("SD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 60, 20));

        jLabel2.setText("MEAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 60, 20));

        pnlGraphDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(pnlGraphDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 990, 600));
        getContentPane().add(txtX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void txtMeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMeanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //w.pnlGraph.add(label);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmExtremities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmExtremities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmExtremities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmExtremities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmExtremities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField4;
    public javax.swing.JPanel pnlGraphDisplay;
    public javax.swing.JTextField txtMean;
    public javax.swing.JTextField txtSD;
    public javax.swing.JTextField txtX1;
    public javax.swing.JTextField txtX2;
    // End of variables declaration//GEN-END:variables
}
