/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package statsmodel;

import java.awt.Color;
import java.math.BigDecimal;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYDifferenceRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
//import statsmodel.Logic.IAreaType;

/**
 *
 * @author st8511x
 */
public class frmGreaterThan extends javax.swing.JFrame { //implements IAreaType {
    //Logic logic;

    // NumericalMethods numMethods = new NumericalMethods();//S.O
    //WorkingOut wO = new 
    ChartPanel chartPanel;
    JFreeChart chart;
    WorkingOut workingOut = new WorkingOut();
    ZTable zTable = new ZTable();

    public frmGreaterThan() {
        initComponents();
        //logic = new Logic();

        chartPanel = new ChartPanel(chart);//prevents new graphs from appending
        txtMean.setText("0");
        txtSD.setText("5");

        ButtonGroup groupZTableArea = new ButtonGroup();//new group for single selection for numerical method used to fill in z table
        // groupZTableArea.add(radBtnZTrap);
        //groupZTableArea.add(radBtnZSimp);

    }

    public void colour_AreaGreaterThan(
            double mean,
            double sdModulo,
            double xOne,
            XYDataset dataset,
            XYPlot plot) {

        XYSeries line = new XYSeries("line");//sequence of data items in (x,y) format
        line.add((xOne), 0);//vertical line @ limit a, user input
        line.add((mean + (4 * sdModulo)), 0);//vertical line @ limit b
        /*XYSeriesCollection: collection of XYSeries objects
         */
        ((XYSeriesCollection) dataset).addSeries(line); //add the two lines to the exisiting normal dist. graph

        XYDifferenceRenderer renderer = new XYDifferenceRenderer(Color.CYAN, Color.CYAN, false);
        renderer.setSeriesPaint(0, Color.BLACK);

        plot.setRenderer(renderer);
    }

    public void showGraphArea(Logic logic, JButton button, boolean s) {
        //sending the controls to display the area 
        logic.showArea(txtMean, txtSD, txtX1, lblOutputArea, s);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGraphDisplay = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtZStart = new javax.swing.JTextField();
        txtZEnd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSimpForTable = new javax.swing.JButton();
        btnTrapForTable = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnTrapForCurve = new javax.swing.JButton();
        btnSimpForCurve = new javax.swing.JButton();
        btnWorking = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtX1 = new javax.swing.JTextField();
        txtSD = new javax.swing.JTextField();
        txtMean = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDisplay = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblOutputArea = new javax.swing.JLabel();
        sP = new javax.swing.JScrollPane();
        pnlZTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Greater Than ");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(400, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlGraphDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 640, 430));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtZStart.setText("1.02");
        txtZStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZStartActionPerformed(evt);
            }
        });
        jPanel2.add(txtZStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 30));

        txtZEnd.setText("1.88");
        txtZEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZEndActionPerformed(evt);
            }
        });
        jPanel2.add(txtZEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 50, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("END");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("START");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        btnSimpForTable.setText("Simpsons");
        btnSimpForTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSimpForTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpForTableActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpForTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 110, 30));

        btnTrapForTable.setText("Trapezium");
        btnTrapForTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTrapForTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrapForTableActionPerformed(evt);
            }
        });
        jPanel2.add(btnTrapForTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 110, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 430, 80));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTrapForCurve.setBackground(new java.awt.Color(255, 255, 255));
        btnTrapForCurve.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnTrapForCurve.setText("Trapezoidal");
        btnTrapForCurve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnTrapForCurve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrapForCurveActionPerformed(evt);
            }
        });
        jPanel3.add(btnTrapForCurve, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 30));

        btnSimpForCurve.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpForCurve.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnSimpForCurve.setText("Simpson's");
        btnSimpForCurve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSimpForCurve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpForCurveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpForCurve, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, 30));

        btnWorking.setBackground(new java.awt.Color(255, 255, 255));
        btnWorking.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnWorking.setText("WORKING OUT");
        btnWorking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnWorking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkingActionPerformed(evt);
            }
        });
        jPanel3.add(btnWorking, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 41, 120, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numerical Methods for Curve Area");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 460, 80));

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel9.setText("Z Table");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 100, 40));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtX1.setText("1.5");
        txtX1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 60, 30));

        txtSD.setText("1");
        txtSD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 60, 30));

        txtMean.setText(" 0");
        txtMean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtMean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMeanActionPerformed(evt);
            }
        });
        jPanel1.add(txtMean, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 30, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MEAN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 130));

        btnDisplay.setBackground(new java.awt.Color(255, 255, 255));
        btnDisplay.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btnDisplay.setText("SHOW GRAPH");
        btnDisplay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 110, 40));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel4.setText("Graph");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOutputArea.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblOutputArea.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lblOutputArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 620, 40));

        sP.setBorder(null);

        pnlZTable.add(jScrollPane1);

        sP.setViewportView(pnlZTable);

        getContentPane().add(sP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 688, 488));

        getAccessibleContext().setAccessibleName("GreaterThan");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void txtMeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMeanActionPerformed

    private void txtX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX1ActionPerformed

    private void btnWorkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkingActionPerformed
        // TODO add your handling code here:
        //workingOut.setVisible(true);
        // WorkingOut.setV

    }//GEN-LAST:event_btnWorkingActionPerformed

    private void txtZStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZStartActionPerformed

    private void txtZEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZEndActionPerformed

    private void btnTrapForCurveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrapForCurveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrapForCurveActionPerformed

    private void btnSimpForCurveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpForCurveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpForCurveActionPerformed

    private void btnSimpForTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpForTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpForTableActionPerformed

    private void btnTrapForTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrapForTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrapForTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //w.pnlGraph.add(label);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGreaterThan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGreaterThan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGreaterThan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGreaterThan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmGreaterThan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnDisplay;
    public javax.swing.JButton btnSimpForCurve;
    public javax.swing.JButton btnSimpForTable;
    public javax.swing.JButton btnTrapForCurve;
    public javax.swing.JButton btnTrapForTable;
    public javax.swing.JButton btnWorking;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblOutputArea;
    javax.swing.JPanel pnlGraphDisplay;
    public javax.swing.JPanel pnlZTable;
    public javax.swing.JScrollPane sP;
    javax.swing.JTextField txtMean;
    javax.swing.JTextField txtSD;
    javax.swing.JTextField txtX1;
    javax.swing.JTextField txtZEnd;
    javax.swing.JTextField txtZStart;
    // End of variables declaration//GEN-END:variables

}
