/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package statsmodel;

import java.awt.*;
import java.awt.image.BufferedImage;
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author st8511x
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form MasterNew
     */
    //Welcome w = new Welcome();
    String p = ".png";

    public Welcome() {
        initComponents();
        // scalePics("a" + p, lblA);
        //scalePics("b" + p, lblB);
        //scalePics("c" + p, lblC);
        //scalePics("d" + p, lblD);

        scalePicsOnBtn("r1" + p, btnGreaterThan);
        scalePicsOnBtn("r2" + p, btnLessThan);
        scalePicsOnBtn("r3" + p, btnBetween);
        scalePicsOnBtn("r4" + p, btnEnds);

        btnGreaterThan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //btnA.setBackground(Color.GREEN);
                scalePicsOnBtn("a" + p, btnGreaterThan);

            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                //btnA.setBackground(UIManager.getColor("control"));
                scalePicsOnBtn("r1" + p, btnGreaterThan);

            }
        });

        btnLessThan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //btnA.setBackground(Color.GREEN);
                scalePicsOnBtn("b" + p, btnLessThan);

            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                //btnA.setBackground(UIManager.getColor("control"));
                scalePicsOnBtn("r2" + p, btnLessThan);

            }
        });

        btnBetween.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //btnA.setBackground(Color.GREEN);
                scalePicsOnBtn("c" + p, btnBetween);

            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                //btnA.setBackground(UIManager.getColor("control"));
                scalePicsOnBtn("r3" + p, btnBetween);

            }
        });

        btnEnds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                //btnA.setBackground(Color.GREEN);
                scalePicsOnBtn("d" + p, btnEnds);

            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                //btnA.setBackground(UIManager.getColor("control"));
                scalePicsOnBtn("r4" + p, btnEnds);

            }
        });

    }

    /*
    public void ResizeImage() {
        Icon icon = lblA.getIcon();
        BufferedImage bi = new BufferedImage(icon.getIconWidth(),
                icon.getIconHeight(), BufferedImage.TYPE_INT_RGB);

        Image newImg = bi.getScaledInstance(lblA.getWidth(), lblA.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lblA.setIcon(image);

    }//delete method

     */
    public void scalePics(String pic, JLabel lbl) {
        String path = "/statsmodel/assets/";
        ImageIcon myImage = new ImageIcon(getClass().getResource(path + pic));
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        lbl.setIcon(image);
    }

    public void scalePicsOnBtn(String pic, JButton btn) {
        String path = "/statsmodel/assets/";
        ImageIcon myImage = new ImageIcon(getClass().getResource(path + pic));
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(btn.getWidth(), btn.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        btn.setIcon(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        btnBetween = new javax.swing.JButton();
        btnLessThan = new javax.swing.JButton();
        btnEnds = new javax.swing.JButton();
        btnGreaterThan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("welcome");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(400, 390));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jTextField4.setText("Select an area of your interest");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 470, 80));
        getContentPane().add(btnBetween, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 350, 220));
        getContentPane().add(btnLessThan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 350, 220));
        getContentPane().add(btnEnds, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 350, 220));
        getContentPane().add(btnGreaterThan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 350, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //w.pnlGraph.add(label);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new Welcome().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBetween;
    public javax.swing.JButton btnEnds;
    public javax.swing.JButton btnGreaterThan;
    public javax.swing.JButton btnLessThan;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
